#!/usr/bin/env python3
"""Rebuild 09-proposal/report-template.html (and wording.json) from their sources.

    python3 scripts/build_template.py

Sources: scripts/plain_language.py (wording), 09-proposal/metric-menu.json
(rules), 09-proposal/src/report.js (layout and logic), 09-proposal/src/report.css.
The template is the single renderer: propose.py fills it from plan.json, and an
assistant using the Ahrefs MCP server fills it from its own counts. Run this
after changing any source, and commit the result.
"""
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import plain_language as PL  # noqa: E402

wording = {k: getattr(PL, k) for k in ("TYPES", "METRICS", "SENTENCE", "STATUS", "SET_TEXT", "FORMULA")}
(ROOT / "09-proposal" / "wording.json").write_text(json.dumps(wording, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
menu = json.loads((ROOT / "09-proposal" / "metric-menu.json").read_text(encoding="utf-8"))
menu = {"metrics": menu["metrics"], "headline_by_shape": menu["headline_by_shape"]}
js = (ROOT / "09-proposal" / "src" / "report.js").read_text(encoding="utf-8")
css = (ROOT / "09-proposal" / "src" / "report.css").read_text(encoding="utf-8")
safe = lambda o: json.dumps(o, ensure_ascii=False).replace("</", "<\\/")  # noqa: E731

html = f"""<!DOCTYPE html>
<!--
  AI visibility dashboard kit: proposal report template.
  Fill it by replacing the JSON inside <script id="measurements"> with your data
  (format: 09-proposal/measurements.md), then open the file in a browser.
  Everything else on the page (labels, verdicts, main numbers, warnings) is
  computed from that JSON, so every run produces the same report.
  Generated by scripts/build_template.py; don't edit by hand.
-->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AI visibility proposal</title>
<style>
{css}</style></head><body><main id="report"></main>
<script type="application/json" id="measurements">
{{"_template": true}}
</script>
<script>
const WORDING = {safe(wording)};
const MENU = {safe(menu)};
{js}</script>
</body></html>
"""
out = ROOT / "09-proposal" / "report-template.html"
out.write_text(html, encoding="utf-8")
print(f"wrote {out} ({len(html)} bytes) and 09-proposal/wording.json")
